services:
  db:
    image: gvenzl/oracle-free:latest
    container_name: maskopy-oracle
    environment:
      ORACLE_PASSWORD: rootpwd
      APP_USER: maskopy
      APP_USER_PASSWORD: maskopypwd
      ORACLE_PATH: /opt/oracle
    ports:
      - "1521:1521"
    volumes:
      - ../db/init.sql:/container-entrypoint-initdb.d/init.sql:ro
      - ../db/login.sql:/opt/oracle/login.sql:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
